language: R
r:
  - oldrel
  - release
  - devel

warnings_are_errors: true

sudo: required

apt_packages:
  - gsl-bin
  - libgsl0-dbg
  - libgsl0-dev
  - libgsl0ldbl
  - libcurl4-openssl-dev
  - libxml2-dev
  - libcgal-dev
  - libglu1-mesa-dev
  - libglu1-mesa-dev
  - libx11-dev

repos:
  CRAN: http://cran.rstudio.com
