dist: trusty

language: R
r:
  - release
  - devel

warnings_are_errors: false

sudo: required

apt_packages:
  - libgsl0-dev
  - libgsl0ldbl
  - libcurl4-openssl-dev
  - libxml2-dev
  - libcgal-dev

repos:
  CRAN: http://cran.rstudio.com
