dist: trusty

language: R
r:
  - oldrel
  - release
  - devel

warnings_are_errors: false

sudo: required

apt_packages:
  - libgsl0-dev
  - libgsl0ldbl
  - libcurl4-openssl-dev
  - libxml2-dev
  - libcgal-dev
  - r-cran-doparallel
  - r-cran-ks
  - r-cran-rcpp
  - r-cran-covr
  - r-cran-testthat

before_install:
  - sudo add-apt-repository ppa:marutter/c2d4u -y
  - sudo apt-get update -q

repos:
  CRAN: http://cran.rstudio.com
